### ISSUE TITLE
Sensors not updating

### ISSUE THREAD

**Issue by Karrelax** [DasBasti/SmartHashtag#102]
Hello,
after the update to 0.3.5, the sensors remain with their last value. 
For example, after the charging process finishes (time limit on the car) the "charging power" remains with its value, instead of dropping to 0W. Same for "charging current", "charger connection" and "charging status". 

The expected outcome is that all of them change when the charging process stops. 

Let me know if some testing is needed.

Best.

## Configuration

```yaml
Add your logs here.
```

## Debug log

```text

Add your logs here.

```

**Comment by wfroemgen** [comment]
Can't confirm. My car is represented perfectly.
![Screenshot_20240602-112910](https://github.com/DasBasti/SmartHashtag/assets/24212615/ef9d7534-ad56-475b-8cb0-38f09e5694fc)
![Screenshot_20240602-112722](https://github.com/DasBasti/SmartHashtag/assets/24212615/fb8434c7-284b-435b-827d-01f74a37e2fc)

**Comment by Karrelax** [comment]
I deleted it and reinstalled it and now it works. Sorry for the mess :/

**Comment by DasBasti** [comment]
> I deleted it and reinstalled it and now it works. Sorry for the mess :/

now worries, I am happy it is working for you!
