### ISSUE TITLE
Tank flap status

### ISSUE THREAD

**Issue by terzo33** [DasBasti/SmartHashtag#117]
Hi @DasBasti , sensor.smart_tank_flap_status doesn't work, show always position "2". Can you fix it?

Thanks a lot

**Comment by DasBasti** [comment]
Hi @terzo33 the data comes from smart web API and is stuck at 2 for me as well. Nothing I can do on this side. The integration just gets all the data that Smart provides from the WebAPI and collects it. I have several other values that did not change, this will be part of a next release to clean out all the sensors that do not really give a reasonable value.
