### ISSUE TITLE
Add long term statistics support

### ISSUE THREAD

**Issue by manutoky** [DasBasti/SmartHashtag#121]
**Is your feature request related to a problem? Please describe.**
The integration seems to not support support long term statistics. As a result, the data is only available for 10 days (default).

**Describe the solution you'd like**
It should be fairly easy to add certain attributes to the entities to enable long term statistics.

**Additional context**
See [smart-1-forum.de](https://www.smart-1-forum.de/forum/thread/336-smart-1-api-smart-home-integration/?postID=100240#post100240) for more context.

**Comment by DasBasti** [comment]
might not be complete.

**Comment by DasBasti** [comment]
https://github.com/DasBasti/SmartHashtag/pull/135 fixes the state_class
