### ISSUE TITLE
Climate switch doesn't work

### ISSUE THREAD

**Issue by terzo33** [DasBasti/SmartHashtag#144]
![Screenshot_20240807_142211_Home Assistant.jpg](https://github.com/user-attachments/assets/555d97da-798d-48e1-a1c4-f4fb4b87daf7)

Hi @DasBasti , why i see climate swith disabled?

Thanks

**Comment by DasBasti** [comment]
Did you update from an older version? The naming changed somewhen in the last months. So please have a look if you can find a newer entity for climate preconditioning.

**Comment by terzo33** [comment]
@DasBasti yes I have 0.4.1 version, i see these entities for climate

![Screenshot_20240807_143717_Home Assistant.jpg](https://github.com/user-attachments/assets/ef79be2c-c8eb-46dd-868a-bcb88c8b8ee9)

**Comment by terzo33** [comment]
I can't control climate on/off with Home Assistant

**Comment by DasBasti** [comment]
![Screenshot_20240807-144058.png](https://github.com/user-attachments/assets/b1a141be-8c33-41b2-9995-c6935e397637)

Can you filter by domain climate and see if you can find it there?

**Comment by terzo33** [comment]
![Screenshot_20240807_144755_Home Assistant.jpg](https://github.com/user-attachments/assets/2d7d926b-6f1e-440d-8ae0-e31b02e30f47)

Yes I found it. Thanks a lot
