### ISSUE TITLE
Trunk entity

### ISSUE THREAD

**Issue by terzo33** [DasBasti/SmartHashtag#145]
Hi @DasBasti , why these two sensors doesn't work?

2 weeks ago worked fine, i saw status of the entities

![Screenshot_20240807_153644_Home Assistant.jpg](https://github.com/user-attachments/assets/9e352e62-90e7-446d-b534-cb862e6d602c)

And these...

![Screenshot_20240807_153902_Home Assistant.jpg](https://github.com/user-attachments/assets/4008ee54-bde2-482e-baf2-c29ec83473f1)

![Screenshot_20240807_153902_Home Assistant.jpg](https://github.com/user-attachments/assets/fffad5ab-7cb1-4dfc-b3c8-321050d9c84a)

![Screenshot_20240807_153928_Home Assistant.jpg](https://github.com/user-attachments/assets/a782d47e-0958-44f4-bbc2-a35444ecc0c3)

**Comment by DasBasti** [comment]
I cleaned up the sensors and you need to activate them from the settings. If you open the device you can find them with this link at the end of the sensors
![grafik](https://github.com/user-attachments/assets/dbdf4dfa-194d-4b43-ba01-1faa912633b0)
select the sensor, click the gear and activate the sensor it should be available again.

**Comment by DasBasti** [comment]
but this shouldn't be in 0.4.2

**Comment by terzo33** [comment]
@DasBasti entity is activated but I see unknown

![Screenshot_20240807_192646_Home Assistant.jpg](https://github.com/user-attachments/assets/f13050ce-8f0a-4c48-89a3-7a6651114953)

**Comment by DasBasti** [comment]
I have no idea whats wrong, maybe you can provide debug logs? The component runs in my HA without issues

**Comment by terzo33** [comment]
after connecting the machine to charge, all the sensors became available and working. I can't explain the reason

**Comment by DasBasti** [comment]
ok, so I will close this since it looks like this was an issue with the API replies.
