### ISSUE TITLE
Time scan update

### ISSUE THREAD

**Issue by terzo33** [DasBasti/SmartHashtag#147]
Hi @DasBasti , until recently I saw that the GPS position was updated every 5/10 seconds (as per my settings), now it updates every 8/10 minutes. why?

making the gps position very inaccurate

![Screenshot_20240809_154308_Home Assistant.jpg](https://github.com/user-attachments/assets/55e68143-2398-4a49-9d3b-811a15562fdc)

![Screenshot_20240809_154628_Home Assistant.jpg](https://github.com/user-attachments/assets/1d10486d-047f-4e85-ad30-ef0855345e69)

**Comment by DasBasti** [comment]
I did not change anything inside the position tracker. But I changed the update frequency setting in the last commits. I will have a look into that. Thanks for reporting.

**Comment by terzo33** [comment]
Thank you so much
