### ISSUE TITLE
Sensore charging Power - bug 

### ISSUE THREAD

**Issue by Criaga** [DasBasti/SmartHashtag#148]
Hi, I can’t integrate my wallbox, I added the entity “sensor.smart_charging_power” on Power Flow card to understand how much I’m charging. 
The problem is that once the charging is stopped, the entity continues to display the last charging power. 
I have to restart the integration to make it work again.

**Comment by DasBasti** [comment]
Thanks for reporting, I will have a look-

**Comment by guggu1** [comment]
seems to work here, version 0.3.5, at least since the beginning of this year until my last charge on August 16th.
![image](https://github.com/user-attachments/assets/ac0bd657-7f6a-44f9-b3bd-91cdca00e7a5)

**Comment by DasBasti** [comment]
I just had a look at my charging history and I found that the DC Charging is still bit buggy. But the value returns to 0 after charging stops. @Criaga can you provide a screenshot of your sensors showing the error?

**Comment by Criaga** [comment]
@DasBasti 

After the last integration update I have had no more problems. Just today I charged the Smart, once finished, the kw value returned to zero. It is not immediate, it took a few minutes but nothing serious 😅
