### ISSUE TITLE
Activate climate control 

### ISSUE THREAD

**Issue by DasBasti** [DasBasti/SmartHashtag#21]
Add support for enabling climate control and heating from HA

**Comment by DasBasti** [comment]
initial work in 1c468e7

**Comment by Flipper81** [comment]
Hello

Can you tell me if this should already work with the climate? I can turn on the air conditioning via HA, but I cannot adjust the temperature. Attention text is translated with translator because I only speak German. Greetings daniel

**Comment by DasBasti** [comment]
Hi Daniel

the climate feature is a work in progress and not really finished. I have little time to work on it at the moment, but since it would be nice to have it I might bump it up the priority list. You can keep watching this issue to get notified if changes are made.

**Comment by Flipper81** [comment]
Hello, what needs to be done so that the temperature can be adjusted? With service climate.turn_on the clima turns on, but I have the feeling that the temperature cannot be set with climate.set_temperature. Greetings Daniel
