### ISSUE TITLE
Motor service hours name

### ISSUE THREAD

**Issue by DasBasti** [DasBasti/SmartHashtag#37]
Three sensors are called "Service due in". But which Service?

**Comment by DasBasti** [comment]
![grafik](https://github.com/DasBasti/SmartHashtag/assets/1713093/dd2d605c-1c6c-4da5-aa6a-d3a444e00bf0)

**Comment by Firehome2022** [comment]
> Three sensors are called "Service due in". But which Service?

I think it means the vehicle inspection fits at least with the kilometres. Only the number of days in the overview does not fit, but it does in the graph. Unfortunately I don't know what the service with the hours is supposed to be, I haven't seen it anywhere.

**Comment by DasBasti** [comment]
The first (15912 h) is called days_to_service and is transferred in days and HA recalculates it in hours.
The second is called engine_hours_to_service and given in hours but is 500 since I own the car.
The third is distance_to_service and is self explanatory.
