### ISSUE TITLE
Setting the update interval based on the engineStatus is not the best solution

### ISSUE THREAD

**Issue by bitzer-git** [DasBasti/SmartHashtag#47]
The default update interval is 5 minutes. It will be changed to 1 minute in case engineStatus is "engine_running". This way it can be delayed between one and five minutes. 

Proposal: If it is possible to get only the parameter vehicleStatus.updateTime from Smart server instead of the entire set it could make sense to get this value every 30 or 60 seconds and compare it to vehicleStatus.updateTime from the last set which was interpreted. If there is a change, the entire set should be requested and interpreted. If there is no change, skip the request and interpretation of the entire set.

**Comment by DasBasti** [comment]
As far as I know from what I get from the API we can only get all the data. But the data is not fetched from the vehicle anyway. The timestamp in the data is updated whenever the data on Smarts Web Service is changed. You should see this in the log of the last_update sensor.
You can select different scan rates for idle, running and charging for the integration from the settings menu

**Comment by guggu1** [comment]
the long update interval is inconvenient with respect to the charging power. I am trying to compute the total energy consumed by the car, and count the number of times I charged. A wait of 5 minutes will result in incorrect numbers for the energy consumed, especially when on a fast charger. During 5 minutes this car charges up to 10kWh.

Any chance the update interval can be shortened?

**Comment by DasBasti** [comment]
On the device view page you can click on configure to open a dialog where you can customise the update interval.![Screenshot_20240421-093558 (1).png](https://github.com/DasBasti/SmartHashtag/assets/1713093/fbcbb1c4-383c-4993-8319-efe28d18e0a2)

You can increase updates during charging there.
![Screenshot_20240421-093757.png](https://github.com/DasBasti/SmartHashtag/assets/1713093/3727a445-4701-4704-8538-f74553c3cfd2)

But keep in mind that the data is fetched from the cloud not from the car. So you are limited by the update frequency of the car to cloud connection.

**Comment by guggu1** [comment]
Danke. Wer Augen hat zu sehen...
