### ISSUE TITLE
V2.6 is displayed as V2.5

### ISSUE THREAD

**Issue by wfroemgen** [DasBasti/SmartHashtag#59]
Homeassistent shows V2.5 in the Integration-Info panel, but V2.6 is installed.
I'm quite sure that V2.6 is active, as the Battery% next to the Device name is the SOC of the Main Battery...
![Screenshot_20240227-084135](https://github.com/DasBasti/SmartHashtag/assets/24212615/34b05f0e-c1cf-43e1-918f-4a67d35ab53e)

**Comment by DasBasti** [comment]
Thanks for reporting. That indeed is an error in the release.
