### ISSUE TITLE
Mapping of some entities not perfect

### ISSUE THREAD

**Issue by bitzer-git** [DasBasti/SmartHashtag#63]
I propose following changes:

smart_charger_connection_status
- should be a state without any unit_of_measurement

smart_12v_batterie_ladestand
- should have the device_class "battery"

smart_aussentemperatur
smart_innentemperatur
- should have the device_class "temperature"

**Comment by DasBasti** [comment]
Device_class "battery" for 12v_batterie_ladestand will confuse HA and display it instead of the high voltage battery in HA Device View

**Comment by bitzer-git** [comment]
You are right, according to the definition of charger_connection_status it should not have a unit but in the development tool from HA I see 

```
unit_of_measurement: 0
attribution: Data provided by http://smart.com/
icon: mdi:battery-unknown
friendly_name: Smart Ladesanschluss
```

Please check line 1043 in sensor.py.
`        return data`

shouldn't it be like 
`        return self.entity_description.native_unit_of_measurement
`
