### ISSUE TITLE
Problem with gps tracker

### ISSUE THREAD

**Issue by terzo33** [DasBasti/SmartHashtag#72]
@DasBasti the gps tracker doesn't update automatically, the only way to get it updated is to restart the smarthashtag integration.  I also tried setting on integration configuration update time of 10 seconds to no avail.  all the other sensors update in real time, this one of the GPS tracker is always still.  
on the official smart application the GPS works correctly.

![Screenshot_20240323_144544_Home Assistant.jpg](https://github.com/DasBasti/SmartHashtag/assets/71357473/8eee0a10-00f0-4c50-9629-8d4fe4f944fc)

**Comment by wfroemgen** [comment]
I can confirm the problem. In some earlier version it did work, if I remember right, but it's hard to tell which Version was running at that time. Probably before the self resetting Privacy Button bug on the cars Software was fixed.

**Comment by terzo33** [comment]
Always Still

![Screenshot_20240324_075555_Home Assistant.jpg](https://github.com/DasBasti/SmartHashtag/assets/71357473/f6c87be0-0a68-452d-9034-f8d6e1373bda)

**Comment by terzo33** [comment]
@DasBasti I just update version to 0.3.2 but why before I saw the status of the vehicle in the home assistant area (work, home ...) and now I only see true or false?

![Screenshot_20240331_131745_Home Assistant.jpg](https://github.com/DasBasti/SmartHashtag/assets/71357473/c1bfda5e-46e4-46ce-a466-d8c8c37a0dc9)

**Comment by DasBasti** [comment]
I experimented with the state of the device tracker according to the "position can be trusted" flag of the GPS data. Updates should work now but I am not satisfied with the state as now either.

If anyone knows how to properly set up the Device Tracker Entity I am very much looking forward for pull requests!

**Comment by terzo33** [comment]
> I experimented with the state of the device tracker according to the "position can be trusted" flag of the GPS data. Updates should work now but I am not satisfied with the state as now either.
> 
> If anyone knows how to properly set up the Device Tracker Entity I am very much looking forward for pull requests!

I agree with you. as a state of the entity it would be better to show the area where the vehicle is located rather than true or false.

in older versions it works perfectly

**Comment by DasBasti** [comment]
> in older versions it works perfectly

But homeassistant seams to have changed since I did not change the code from the first version of the device tracker entity

**Comment by terzo33** [comment]
@DasBasti is there a way to fix this problem? I need to read gps area(home, not home, work) for automation

**Comment by DasBasti** [comment]
I will have a look into it tomorrow. Maybe there needs to be a different type of entity.

**Comment by terzo33** [comment]
> I will have a look into it tomorrow. Maybe there needs to be a different type of entity.

Thanks a lot
