### ISSUE TITLE
Device Tracker Data not Updating at Startup

### ISSUE THREAD

**Issue by DasBasti** [DasBasti/SmartHashtag#78]
The DeviceTracker entity does not populate with data from the first update. Only the second update is populating the sensor values.

**Comment by guggu1** [comment]
the Device tracker has not updated the last few days. I have used the car and also reloaded the integration, the did at least 3 rides

**Comment by guggu1** [comment]
… one hour later: I have reloaded the integration (again) - tracker is working, without the car having been used. ???

**Comment by DasBasti** [comment]
device tracker seams to work reliably now. At least for my installation
