### ISSUE TITLE
Not an issue, just info about charging

### ISSUE THREAD

**Issue by Karrelax** [DasBasti/SmartHashtag#83]
Hi,
Not sure if this is the correct place, but I saw on the main table page that "Charger Connection Status" indicates "Need to determine what number means what". 
well, here it is:
0 means "not connected"
2 means "plugged, not charging"
3 means "Charging"
Also for "Is Charger Connected", what in realty indicates is if it is charging (true) or not charging (false), but stays in false in case you have it connected but not charging. 

some other sensors: 
GPS position works smoothly. 
PM2.5/25.2 particle levels do not show anything. 
Some of sensors are not relevant for smart#3 (and I think neither for smart#1) as "curtain open status", "sun curtain rear open status" or "sunroof position". 
"Tank flap status" does not change at all. 
"trunk open status" does not change at all (instead, "trunk lock status" shows the status of the trunk, "1" for close, "2" for open.

If you need to test stuff, I am happily using your integration with my brand new Smart#3 15th anniversary, just let me know :)

Regards,

**Comment by DasBasti** [comment]
Thanks for the input. I hadn't had time to investigate all the sensor names and their actual state so this information is very handy
